// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: WES

#ifndef _WES_UI_H
#define _WES_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "freertos/idf_additions.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_ChatScreen.h"

///////////////////// VARIABLES ////////////////////

static QueueHandle_t *send_queue;
// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_474848270);    // assets/send-message-svgrepo-com.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
