// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: WES

#include "ui.h"

void send_message(lv_event_t * e)
{
	// Your code here
}
