// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: WES

#include "ui.h"

static void add_padding(lv_obj_t *label)
{
    lv_obj_set_style_pad_left(label, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(label, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(label, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void recieve_message(const char *text)
{
	// recv msg
	int cnt = lv_obj_get_child_cnt(ui_TextContainer);
	lv_obj_t *curr, *prev;
	curr = lv_obj_get_child(ui_TextContainer, cnt-1);
	for(int i=cnt-2; i>=0; --i)
	{
		prev = curr;
		curr = lv_obj_get_child(ui_TextContainer, i);
		const char *temp = lv_label_get_text(curr);
		if(*temp != '\0') {
			add_padding(prev);
			lv_label_set_text(prev, lv_label_get_text(curr));
		}
	}
	add_padding(curr);
	lv_label_set_text(curr, text);
}

void send_message(lv_event_t * e)
{
	const char *text = lv_textarea_get_text(ui_MsgArea);
	recieve_message(text);
	// tcp send
	lv_textarea_set_text(ui_MsgArea, "");
}
