// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: WES

#include "../ui.h"

lv_obj_t * ui_ChatScreen = NULL;
lv_obj_t * ui_Keyboard = NULL;
lv_obj_t * ui_MsgArea = NULL;
lv_obj_t * ui_SendBtn = NULL;
lv_obj_t * ui_BtnImg = NULL;
lv_obj_t * ui_TextContainer = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label9 = NULL;
// event funtions
void ui_event_MsgArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_state_modify(ui_Keyboard, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_basic_set_property(ui_TextContainer, _UI_BASIC_PROPERTY_HEIGHT,  68);
        _ui_basic_set_property(ui_MsgArea, _UI_BASIC_PROPERTY_POSITION_Y,  80);
        _ui_basic_set_property(ui_SendBtn, _UI_BASIC_PROPERTY_POSITION_Y,  -22);
        _ui_keyboard_set_target(ui_Keyboard,  ui_MsgArea);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_state_modify(ui_Keyboard, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_flag_modify(ui_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_basic_set_property(ui_TextContainer, _UI_BASIC_PROPERTY_HEIGHT,  184);
        _ui_basic_set_property(ui_MsgArea, _UI_BASIC_PROPERTY_POSITION_Y,  197);
        _ui_basic_set_property(ui_SendBtn, _UI_BASIC_PROPERTY_POSITION_Y,  96);
    }
}

void ui_event_SendBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        send_message(e);
    }
}

// build funtions

void ui_ChatScreen_screen_init(void)
{
    ui_ChatScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ChatScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ChatScreen, lv_color_hex(0x8A8A8A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChatScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ChatScreen, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ChatScreen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard = lv_keyboard_create(ui_ChatScreen);
    lv_obj_set_width(ui_Keyboard, 300);
    lv_obj_set_height(ui_Keyboard, 120);
    lv_obj_set_align(ui_Keyboard, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_state(ui_Keyboard, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_Keyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_MsgArea = lv_textarea_create(ui_ChatScreen);
    lv_obj_set_width(ui_MsgArea, lv_pct(85));
    lv_obj_set_height(ui_MsgArea, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_MsgArea, -20);
    lv_obj_set_y(ui_MsgArea, 197);
    lv_obj_set_align(ui_MsgArea, LV_ALIGN_TOP_MID);
    lv_textarea_set_placeholder_text(ui_MsgArea, "Write message here");
    lv_textarea_set_one_line(ui_MsgArea, true);

    ui_SendBtn = lv_btn_create(ui_ChatScreen);
    lv_obj_set_width(ui_SendBtn, 30);
    lv_obj_set_height(ui_SendBtn, 30);
    lv_obj_set_x(ui_SendBtn, 137);
    lv_obj_set_y(ui_SendBtn, 96);
    lv_obj_set_align(ui_SendBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SendBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SendBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SendBtn, lv_color_hex(0xE6E983), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SendBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnImg = lv_img_create(ui_SendBtn);
    lv_img_set_src(ui_BtnImg, &ui_img_474848270);
    lv_obj_set_width(ui_BtnImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BtnImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BtnImg, 64);

    ui_TextContainer = lv_obj_create(ui_ChatScreen);
    lv_obj_remove_style_all(ui_TextContainer);
    lv_obj_set_height(ui_TextContainer, 180);
    lv_obj_set_width(ui_TextContainer, lv_pct(94));
    lv_obj_set_x(ui_TextContainer, lv_pct(3));
    lv_obj_set_y(ui_TextContainer, lv_pct(3));
    lv_obj_clear_flag(ui_TextContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_TextContainer);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, -46);
    lv_obj_set_align(ui_Label2, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label2, "");

    ui_Label3 = lv_label_create(ui_TextContainer);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -23);
    lv_obj_set_align(ui_Label3, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label3, "");

    ui_Label4 = lv_label_create(ui_TextContainer);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label4, "");

    ui_Label5 = lv_label_create(ui_TextContainer);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, -69);
    lv_obj_set_align(ui_Label5, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label5, "");

    ui_Label6 = lv_label_create(ui_TextContainer);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -92);
    lv_obj_set_align(ui_Label6, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label6, "");

    ui_Label7 = lv_label_create(ui_TextContainer);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, -115);
    lv_obj_set_align(ui_Label7, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label7, "");

    ui_Label8 = lv_label_create(ui_TextContainer);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, -138);
    lv_obj_set_align(ui_Label8, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label8, "");

    ui_Label9 = lv_label_create(ui_TextContainer);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, -161);
    lv_obj_set_align(ui_Label9, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label9, "");

    lv_obj_add_event_cb(ui_MsgArea, ui_event_MsgArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SendBtn, ui_event_SendBtn, LV_EVENT_ALL, NULL);

}

void ui_ChatScreen_screen_destroy(void)
{
    if(ui_ChatScreen) lv_obj_del(ui_ChatScreen);

    // NULL screen variables
    ui_ChatScreen = NULL;
    ui_Keyboard = NULL;
    ui_MsgArea = NULL;
    ui_SendBtn = NULL;
    ui_BtnImg = NULL;
    ui_TextContainer = NULL;
    ui_Label2 = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;
    ui_Label5 = NULL;
    ui_Label6 = NULL;
    ui_Label7 = NULL;
    ui_Label8 = NULL;
    ui_Label9 = NULL;

}
