// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: WES

#ifndef UI_CHATSCREEN_H
#define UI_CHATSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ChatScreen
extern void ui_ChatScreen_screen_init(void);
extern void ui_ChatScreen_screen_destroy(void);
extern lv_obj_t * ui_ChatScreen;
extern lv_obj_t * ui_Keyboard;
extern void ui_event_MsgArea(lv_event_t * e);
extern lv_obj_t * ui_MsgArea;
extern void ui_event_SendBtn(lv_event_t * e);
extern lv_obj_t * ui_SendBtn;
extern lv_obj_t * ui_BtnImg;
extern lv_obj_t * ui_TextContainer;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

